### ISSUE TITLE
人脸识别模块失效

### ISSUE THREAD

**Issue by yuanliangxie** [hpc203/libface-detect-recognition#2]
你好，经过简单的测试，该代码中提取的特征向量识别准确度较差，不知道是不是权重没转好的缘故。相似度度量的值相差都很小，难以区分不同的人脸

**Comment by hpc203** [comment]
这套代码比较旧了，我的仓库里发布了新的libface人脸检测+SFace提取人脸特征向量的程序，建议用新的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月31日(周四) 下午3:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [hpc203/libface-detect-recognition] 人脸识别模块失效 (Issue #2)




 
你好，经过简单的测试，该代码中提取的特征向量识别准确度较差，不知道是不是权重没转好的缘故。相似度度量的值相差都很小，难以区分不同的人脸

**Comment by hpc203** [comment]
> 你好，经过简单的测试，该代码中提取的特征向量识别准确度较差，不知道是不是权重没转好的缘故。相似度度量的值相差都很小，难以区分不同的人脸

用这个新的
https://github.com/hpc203/libface-sface_detect-recognition-opencv

**Comment by yuanliangxie** [comment]
非常感谢！
